apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quote
    role: business
    type: service
  name: quote
spec:
  replicas: {{.Values.quote.replicaCount}}
  selector:
    matchLabels:
      app: quote
      role: business
      type: service
  template:
    metadata:
      labels:
        app: quote
        role: business
        type: service
    spec:
      containers:
      - env:
        - name: mongoquotesvc
          value: mongo-quote-0.mongoquotesvc:27017,mongo-quote-1.mongoquotesvc:27017,mongo-quote-2.mongoquotesvc:27017
        - name: partysvc
          value: partysvc
        image: {{.Values.quote.repository}}:{{.Values.quote.tag}}
        imagePullPolicy: {{.Values.quote.pullPolicy}} 
        name: quote
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /isready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 25
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 25
        resources:
          requests:
            memory: {{.Values.quote.memoryRequests}}
            cpu: {{.Values.quote.cpuRequests}}
          limits:
            memory: {{.Values.quote.memoryLimits}}
            cpu: {{.Values.quote.cpuLimits}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quote
    role: business
    type: service
  name: quote-svc
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: quote-mapping
      prefix: /api/v1/healths/quotes
      service: quote-svc:8000
      rewrite: "" 
spec:
  ports:
  - port: 8000
    name: backend
    targetPort: 8000
  selector:
    app: quote
    role: business
    type: service
  type: NodePort
