apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo-receipt
    tier: backend
  name: mongo-receipt
spec:
  serviceName: mongoreceiptsvc
  replicas: {{.Values.mongo.replicaCount}}
  selector:
    matchLabels:
      app: mongo-receipt
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-receipt
        tier: backend
    spec:
      containers:
      - image: {{.Values.mongo.repository}}:{{.Values.mongo.tag}}  
        name: mongo-receipt
        command:
          - mongod  
          - "--replSet"
          - rs0 
          - "--bind_ip"  
          - 0.0.0.0     
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
        livenessProbe:
          exec: 
            command:
            - mongo
            - --eval
            - db.serverStatus() 
        resources:
          requests:
            memory: {{.Values.mongo.memoryRequests}}
            cpu: {{.Values.mongo.cpuRequests}}
          limits:
            memory: {{.Values.mongo.memoryLimits}}
            cpu: {{.Values.mongo.cpuLimits}}  
  volumeClaimTemplates: 
  - metadata:
      name: data
      annotations: 
        volume.alpha.kubernetes.io/storage-class: default
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources: 
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-receipt
    tier: backend
  name: mongoreceiptsvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-receipt
    tier: backend
  clusterIP: None
