apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: receipt
    role: business
    type: service
  name: receipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt
      role: business
      type: service
  template:
    metadata:
      labels:
        app: receipt
        role: business
        type: service
    spec:
      containers:
      - env:
        - name: mongoreceiptsvc
          value: mongo-receipt-0.mongoreceiptsvc:27017,mongo-receipt-1.mongoreceiptsvc:27017,mongo-receipt-2.mongoreceiptsvc:27017
        image: bikertales/receipt:v1
        name: receipt
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: receipt
    role: business
    type: service
  name: receipt-svc
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: receipt-health
      prefix: /api/v1/receipts
      service: receipt-svc:8000
      rewrite: "" 
spec:
  ports:
  - port: 8000
    name: backend
    targetPort: 8000
  selector:
    app: receipt
    role: business
    type: service
  type: NodePort  
