apiVersion: v1
kind: Secret
metadata:
  name: kafka-cc-secret
type: Opaque
data:
  password: MXlYTUVaTWp5NzJRaFcxbFNZd0pwcFJQcWQ5d3VPdDFURG5NOHFRbUU4MU82M0wzU05KdUdJakhIUHdLSTFiYw==
  username: TllLRUdNUDVNNU1BUldHVQ==