service:
  type: ClusterIP
  port: 80

policy: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 1
  repository: bikertales/policy
  tag: a8f0f8d4b51af7d1472ca7c7a61c663f39bc7bd8
  pullPolicy: IfNotPresent
  mysql:
    user: root
    password: AgCoQ5GrNE/kKlE20qTL/ruyOTHF/gXoaXlNzUTrQCa/a2Dh7Vz2I2fyUL48fRh30M5TAQ7G7auYVFuiHjmcL4gJ+F+tKjcZHHLbBvH+s9aflhoS2QM2J+MKPd/eDKQwz4BrejSHuAlbPQLs8aR49qKoURjzzeWuxhzW26o2NVs2mdYPDGc3KkMKRQk/dNOsyWif3de+eaGBcDrBxzsEvWQgHh999jhr36oPMpuLI4W+2a0bIGnBWa7PUUgkIo1sYvhyerWrmQoxys9MmuFWS6KQBK91mO35XnZWLBp4mB8W5Wjng3R6pPal7w0YVMEroswFgzVwdKsabm6S8/IYjvcpBKlEJ3myQmkcETYZ0sKlpznqLRXdSznfOmmmqCwPydWnmPE2Nv/uEls+FRhcogi97YBa4vX8TcbrkEIv+uPpn3RwW1j6YZlUzD5j8E4UCIZXKh6zLNiqhRPoQBLIthPXnX9djt/5K/pH6/N50xwqNT8TCx2zRRHffsQ9cdMCyCK3rTsKzbuJp0FnxZoIrdugXD2Ngt4LGwCaZmaHaC9ASLS9h9BSkzXTHfN/bsvqkvxUj4SoBpoLed4vYlRgORqOjE5Czkmfal7CopMwrRjUsg6obIkP7LK+FXumlrPYfqxjjA4Udh0LPFNjI58a60X8AmhqQhVUC2/spk+U/vSzDOTVy/CcPnyHdoQGlddAiswFgPs8r+eoFms=
    svc: mysql-policy