service:
  type: ClusterIP
  port: 80

policy: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 1
  repository: bikertales/policy
  tag: a1d22c92461be5548b17c7ceab179aa0d5aa3ef2 
  pullPolicy: IfNotPresent
  mysql:
    user: policy
    password: cG9saWN5MTIz
    svc: mysql-policy-external-svc  
  publisher:
    svc: publishersvc  