service:
  type: ClusterIP
  port: 80

policy: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 1
  repository: bikertales/policy
  tag: v0.2
  pullPolicy: IfNotPresent
