apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo-party
    tier: backend
  name: mongo-party
spec:
  serviceName: mongopartysvc
  replicas: {{.Values.mongo.replicaCount}}
  selector:
    matchLabels:
      app: mongo-party
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-party
        tier: backend
    spec:
      containers:
      - image: {{.Values.mongo.repository}}:{{.Values.mongo.tag}} 
        imagePullPolicy: {{.Values.mongo.pullPolicy}} 
        name: mongo-party
        command:
          - mongod  
          - "--replSet"
          - rs0 
          - "--bind_ip"  
          - 0.0.0.0     
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
        resources:
          requests:
            memory: {{.Values.mongo.memoryRequests}}
            cpu: {{.Values.mongo.cpuRequests}}
          limits:
            memory: {{.Values.mongo.memoryLimits}}
            cpu: {{.Values.mongo.cpuLimits}}  
  volumeClaimTemplates: 
  - metadata:
      name: data
      annotations: 
        storageclass.kubernetes.io/is-default-class: "true"
    spec: 
      accessModes: 
      - ReadWriteOnce
      resources: 
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-party
    tier: backend
  name: mongopartysvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-party
    tier: backend
  clusterIP: None
