apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: party
    role: business
    tier: backend
  name: party
spec:
  replicas: {{.Values.party.replicaCount}}
  selector:
    matchLabels:
      app: party
      role: business
      tier: backend
  template:
    metadata:
      labels:
        app: party
        role: business
        tier: backend
    spec:
      containers:
      - image: {{.Values.party.repository}}:{{.Values.party.tag}}
        name: party
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - /opt/grpc-health-probe
            - -addr=:50051
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          exec:
            command: 
            - /opt/grpc-health-probe
            - -addr=:50051
          initialDelaySeconds: 5
          periodSeconds: 15
        env:
        - name: mongopartysvc
          value: mongo-party-0.mongopartysvc:27017,mongo-party-1.mongopartysvc:27017,mongo-party-2.mongopartysvc:27017
        resources:
          requests:
            memory: {{.Values.party.memoryRequests}}
            cpu: {{.Values.party.cpuRequests}}
          limits:
            memory: {{.Values.party.memoryLimits}}
          cpu: {{.Values.party.cpuLimits}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: party
    role: business
    tier: backend
  name: partysvc
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
    name: grpc-party
  selector:
    app: party
    role: business
    tier: backend
