apiVersion: v1
kind: Service
metadata:
  labels:
    app: premium
    role: business
    type: backend
  name: premiumcalc-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: http-premium
  selector:
    app: premium
    role: business
    type: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: premium
    role: business
    type: backend
    version: v1
  name: premiumcalc-v1
spec:
  replicas: {{.Values.premiumcalc.replicaCount}}
  selector:
    matchLabels:
      app: premium
      role: business
      type: backend
      version: v1
  template:
    metadata:
      labels:
        app: premium
        role: business
        type: backend
        version: v1
    spec:
      containers:
      - image: {{.Values.premiumcalc.repository}}:{{.Values.premiumcalc.v1Tag}}
        imagePullPolicy: {{.Values.premiumcalc.pullPolicy}} 
        name: premiumcalc
        ports:
        - containerPort: 8000
        env: 
        - name: redissvc
          value: redissvc
        readinessProbe:
          httpGet:
            path: /api/v1/healths/premiums/loads
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10          
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10  
        resources:
          requests:
            memory: {{.Values.premiumcalc.memoryRequests}}
            cpu: {{.Values.premiumcalc.cpuRequests}}
          limits:
            memory: {{.Values.premiumcalc.memoryLimits}}
            cpu: {{.Values.premiumcalc.cpuLimits}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: premium
    role: business
    type: backend
    version: v2
  name: premiumcalc-v2
spec:
  replicas: {{.Values.premiumcalc.replicaCount}}
  selector:
    matchLabels:
      app: premium
      role: business
      type: backend
      version: v2
  template:
    metadata:
      labels:
        app: premium
        role: business
        type: backend
        version: v2
    spec:
      containers:
      - image: {{.Values.premiumcalc.repository}}:{{.Values.premiumcalc.v2Tag}}
        imagePullPolicy: {{.Values.premiumcalc.pullPolicy}} 
        name: premiumcalc
        ports:
        - containerPort: 8000
        env: 
        - name: redissvc
          value: redissvc
        readinessProbe:
          httpGet:
            path: /api/v1/healths/premiums/loads
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10          
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10  
        resources:
          requests:
            memory: {{.Values.premiumcalc.memoryRequests}}
            cpu: {{.Values.premiumcalc.cpuRequests}}
          limits:
            memory: {{.Values.premiumcalc.memoryLimits}}
            cpu: {{.Values.premiumcalc.cpuLimits}}            