apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: master
    tier: backend
  name: redissvc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    role: master
    tier: backend
data:
  master.conf: |- 
    bind 0.0.0.0
    port 6379
    save 900 1
    dir /redis-data
  slave.conf: |-
    bind 0.0.0.0
    port 6379
    dir .
    slaveof redis-premium-master-0.redissvc.default.svc.cluster.local 6379
  sentinel.conf: |- 
    bind 0.0.0.0
    port 26379
    sentinel monitor redis-premium-master redis-premium-master-0.redissvc.default.svc.cluster.local 6379 2
    sentinel parallel-syncs redis-premium-master 1
    sentinel down-after-milliseconds redis-premium-master 10000
    sentinel failover-timeout redis-premium-master 20000
  sentinel.sh: |- 
    #!/bin/bash
    cp /redis-config/sentinel.conf /sentinel.conf
    while ! ping -c 1 redis-premium-master-0.redissvc.default.svc.cluster.local; do
      echo 'Waiting for server'
      sleep 1
    done
    redis-sentinel /sentinel.conf
  init.sh: |-
    #!/bin/bash
    if [[ ${HOSTNAME} == 'redis-premium-master-0' ]]; then
      redis-server /redis-config/master.conf
    else
      redis-server /redis-config/slave.conf
    fi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-premium-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: {{.Values.redis.replicaCount}}
  serviceName: redissvc
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend 
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - command: [sh, -c, source /redis-config/init.sh]
        image: redis:{{.Values.redis.tag}}
        imagePullPolicy: {{.Values.redis.pullPolicy}}
        name: redis
        ports: 
        - containerPort: 6379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config
        livenessProbe:
          tcpSocket: 
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
        resources:
          requests:
            memory: {{.Values.redis.memoryRequests}}
            cpu: {{.Values.redis.cpuRequests}}
          limits:
            memory: {{.Values.redis.memoryLimits}}
            cpu: {{.Values.redis.cpuLimits}}
      - command: [sh, -c, source /redis-config/sentinel.sh]
        image: redis:3.2.7-alpine
        name: sentinel
        ports:
        - containerPort: 26379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config          
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 5
      volumes: 
      - configMap: 
          defaultMode: 420
          name: redis-config
        name: config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    spec:
      #storageClassName: standard  
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: premium
    role: business
    type: backend
  name: premiumcalc
spec:
  replicas: {{.Values.premiumcalc.replicaCount}}
  selector:
    matchLabels:
      app: premium
      role: business
      type: backend
  template:
    metadata:
      labels:
        app: premium
        role: business
        type: backend
    spec:
      containers:
      - image: {{.Values.premiumcalc.repository}}:{{.Values.premiumcalc.tag}}
        imagePullPolicy: {{.Values.premiumcalc.pullPolicy}} 
        name: premiumcalc
        ports:
        - containerPort: 8000
        env: 
        - name: redissvc
          value: redissvc  
        readinessProbe:
          httpGet:
            path: /api/v1/healths/premiums/loads
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10          
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10  
        resources:
          requests:
            memory: {{.Values.premiumcalc.memoryRequests}}
            cpu: {{.Values.premiumcalc.cpuRequests}}
          limits:
            memory: {{.Values.premiumcalc.memoryLimits}}
            cpu: {{.Values.premiumcalc.cpuLimits}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: premium
    role: business
    type: backend
  name: premiumcalc-svc
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: premium-mapping
      prefix: /api/v1/healths/premiums
      service: premiumcalc-svc:8000
      rewrite: ""
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: premium
    role: business
    type: backend  
  type: NodePort
