replicaCount: 1

image:
  repository: quay.io/fluentd_elasticsearch/fluentd
  tag: v2.6.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 150m 
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi
