apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubesure
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/healths/premiums
        backend:
          serviceName: premiumcalc-svc
          servicePort: 8000
  rules:
  - http:
      paths:
      - path: /api/v1/receipts
        backend:
          serviceName: receipt-svc
          servicePort: 8000
