redis:
  replicaCount: 3
premium:
  replicaCount: 2

imagepremium:
  repository: premiumcalc
  tag: v0.2
  pullPolicy: IfNotPresent
imageredis:
  repository: redis
  tag: 3.2.7-alpine    

service:
  type: ClusterIP
  port: 8000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

