service:
  type: ClusterIP
  port: 8000

redis: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 3
  repository: redis
  tag: 3.2.7-alpine
  pullPolicy: IfNotPresent
premiumcalc:
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 2
  repository: bikertales/premiumcalc
  tag: v0.2
  pullPolicy: IfNotPresent
