service:
  type: ClusterIP
  port: 8000

redis: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 3
  repository: redis
  tag: 3.2.7-alpine
  pullPolicy: IfNotPresent
premiumcalc:
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 2
  repository: bikertales/premiumcalc
  v1Tag: v0.2
  v2Tag: f364458104c38103c6fbf15d2445306ade9d007d
  pullPolicy: IfNotPresent
