#kind: Service
#apiVersion: v1
#metadata:
#  name: mysql-policy-external-svc
#spec:
#  type: ExternalName
#  externalName: host.minikube.internal
apiVersion: v1
kind: Service
metadata:
  name: mysql-policy-external-svc
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-policy-external-svc
subsets:
  - addresses:
      - ip: 192.168.39.1
    ports:
      - port: 3306