apiVersion: v1
data:
  password: cG9saWN5MTIzCg==
kind: Secret
metadata:
  name: mysql-policy-pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: policy
    role: business
    type: service
  name: policy
spec:
  replicas: {{.Values.policy.replicaCount}}
  selector:
    matchLabels:
      app: policy
      role: business
      type: service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: policy
        role: business
        type: service
    spec:
      containers:
      - image: {{.Values.policy.repository}}:{{.Values.policy.tag}}
        name: policy
        ports:
        - containerPort: 8000
        env: 
        - name: mysqlpolicysvc
          value: mysql-policy-pxc-0.mysql-policy-pxc
        - name: POLICY_DB_USR
          value: policy
        - name: POLICY_DB_USR_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-policy-pass
              key: password  
        resources:
          requests:
            memory: {{.Values.policy.memoryRequests}}
            cpu: {{.Values.policy.cpuRequests}}
          limits:
            memory: {{.Values.policy.memoryLimits}}
            cpu: {{.Values.policy.cpuLimits}}  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: policy
    role: business
    type: service
  name: policy-svc
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: policy-mapping
      prefix: /api/v1/health/poicies
      service: policy-svc:8000
      rewrite: "" 
spec:
  ports:
  - port: 8000
    name: backend
    targetPort: 8000
  selector:
    app: policy
    role: business
    type: service
  type: NodePort  
