service:
  type: ClusterIP
  port: 80

publisher: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 2
  repository: bikertales/publisher
  tag: 7d785e59f46c6b66441a327b3bba6ff589fe45f1
  pullPolicy: IfNotPresent
  kafkaServerHost: pkc-4nym6.us-east-1.aws.confluent.cloud  
  kafkaServerPort: 9092
