service:
  type: ClusterIP
  port: 80

publisher: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 2
  repository: bikertales/publisher
  tag: 88990d2bec5ea14399335e450003cdc6cdee9d49
  pullPolicy: IfNotPresent
  kafkaServerHost: 52.90.158.247
  kafkaServerPort: 9092
