service:
  type: ClusterIP
  port: 80

party: 
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 2
  repository: bikertales/party
  tag: v0.2
  pullPolicy: IfNotPresent
mongo:
  cpuRequests: 100m
  memoryRequests: 200Mi
  cpuLimits: 200m
  memoryLimits: 250Mi
  replicaCount: 3
  repository: mongo
  tag: 4.0.9
  pullPolicy: IfNotPresent
