apiVersion: v1
kind: ConfigMap
metadata:
  name: comms-kafka-config
  labels:
    app: comms
    role: business
    tier: event
data:
  application.properties: |-
    spring.kafka.bootstrap-servers=54.81.213.85:9092
