apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comms
    role: business
    type: event
  name: comms
spec:
  replicas: {{.Values.comms.replicaCount}}
  selector:
    matchLabels:
      app: comms
      role: business
      type: event
  template:
    metadata:
      labels:
        app: comms
        role: business
        type: event
    spec:
      volumes:
      - name: kafka-config
        configMap:
          name: comms-kafka-config
      #- name: aws-config
        #configMap:
          #name: comms-aws-config 
      containers:
      - image: {{.Values.comms.repository}}:{{.Values.comms.tag}}
        name: comms
        imagePullPolicy: {{.Values.comms.pullPolicy}}
        volumeMounts:
        - name: kafka-config
          mountPath: /etc/comms
        #- name: aws-config
          #mountPath: /.aws 
        env:
        - name: SPRING_CONFIG_LOCATION
          value: /etc/comms/application.properties
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef: 
              name: comms-aws-secret
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: comms-aws-secret
              key: aws-secret-access-key
        - name: CC_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-comms-secret
              key: username
        - name: CC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-comms-secret
              key: password          
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"] 
        resources:
          requests:
            memory: {{.Values.comms.memoryRequests}}
            cpu: {{.Values.comms.cpuRequests}}
          limits:
            memory: {{.Values.comms.memoryLimits}}
            cpu: {{.Values.comms.cpuLimits}} 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20          
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10